import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css"; // Make sure this path is correct
import Navbar from "../components/Navbar/Navbar"
import {ToastContainer, toast} from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


// Import Outfit font
const outfit = Outfit({
  weight: ["400", "500", "600", "700"], // Include weights you need
  subsets: ["latin"], // Include subsets you need
  display: "swap", // Ensures text remains visible during font load
});

export const metadata: Metadata = {
  title: "Admin panel for BookMovie",
  description: "Generated by Sabari Vijayan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>      
        <Navbar/>
        <ToastContainer position="top-center" autoClose={5000} hideProgressBar={false}
        newestOnTop={false} closeOnClick rtl={false} pauseOnFocusLoss={false}
        draggable pauseOnHover={false} />
        {children}</body>
    </html>
  );
}
